import { StyleSheet } from 'react-native';
import { fontWeight, lineHeight, radius, spacing, typeScale, type ThemeColors } from '@/theme';
export const makeTodoStyles = (c: ThemeColors) =>
  StyleSheet.create({
    content: {
      paddingHorizontal: spacing.lg,
      paddingBottom: spacing.lg,
      gap: spacing.sm,
    },
    toolbar: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
    flex: { flex: 1, minWidth: 0 },
    row: {
      paddingVertical: spacing.sm,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
      minWidth: 0,
    },
    heading: { minHeight: 46, minWidth: 0 },
    title: {
      fontSize: typeScale.subtitle,
      lineHeight: lineHeight.subtitle,
      fontWeight: fontWeight.medium,
      color: c.textPrimary,
    },
    progress: {
      fontSize: typeScale.bodySmall,
      lineHeight: lineHeight.bodySmall,
      fontWeight: fontWeight.regular,
      color: c.textSecondary,
    },
    rail: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      marginTop: spacing.sm,
      minHeight: 44,
    },
    date: { flex: 1, minWidth: 0, minHeight: 44, justifyContent: 'center' },
    caption: {
      fontSize: typeScale.caption,
      lineHeight: lineHeight.caption,
      fontWeight: fontWeight.regular,
      color: c.textSecondary,
    },
    action: {
      width: 144,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: spacing.sm,
      borderRadius: radius.pill,
      backgroundColor: c.surfaceChip,
    },
    actionText: {
      fontSize: typeScale.bodySmall,
      lineHeight: lineHeight.bodySmall,
      fontWeight: fontWeight.medium,
      color: c.textPrimary,
      maxWidth: '100%',
    },
    icon: {
      width: 44,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    button: {
      minHeight: 44,
      paddingHorizontal: spacing.sm,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: radius.control,
      backgroundColor: c.surfaceChip,
    },
    buttonText: {
      fontSize: typeScale.bodySmall,
      lineHeight: lineHeight.bodySmall,
      fontWeight: fontWeight.medium,
      color: c.textPrimary,
    },
    disabled: { opacity: 0.5 },
    body: {
      fontSize: typeScale.bodySmall,
      lineHeight: lineHeight.bodySmall,
      fontWeight: fontWeight.regular,
      color: c.textPrimary,
    },
    field: { gap: spacing.xs },
    input: {
      minHeight: 44,
      padding: spacing.sm,
      borderRadius: radius.control,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      color: c.textPrimary,
      fontSize: typeScale.bodySmall,
      lineHeight: lineHeight.bodySmall,
      fontWeight: fontWeight.regular,
      backgroundColor: c.surfaceElevated,
    },
    disclosure: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
      minHeight: 44,
    },
  });
